name: tamil_project
description: "Tamil AI App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:

  flutter_tts: ^3.8.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔥 API CALL
  http: ^0.13.6

  # 🔐 TOKEN STORAGE
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/security.png
    - assets/images/book_glow.png
    - assets/images/rephraser.png
    - assets/images/sentence.png
    - assets/images/history.png
    - assets/images/translator.png
    - assets/images/brain.png